=== bfh-evg/univote2/json-schemas/client/listElectionIssueSchema.json
{
	"$schema": "http://json-schema.org/draft-04/schema",
	"title": "UniVote2: Schema of a list election issue",
	"type": "object",

	"properties": {
		"id": {
			"description": "Issue identifier (unique within election)",
			"type": "integer"
		},
		"type": {
			"description": "Issue type",
			"enum": ["listElection"]
		},
		"title": {
			"description": "Election title",
			"$ref": "i18nTextSchema.json"
		},
		"description": {
			"description": "Election description",
			"$ref": "i18nTextSchema.json"
		},
		"options": {
			"description": "Container of election options",
			"type": "array",
			"items": {
				"oneOf": [
					{ "$ref": "listOptionSchema.json" },
					{ "$ref": "candidateOptionSchema.json" }
				]
			}
		},
		"rules": {
			"description": "Container of election rules",
			"type": "array",
			"items": {
				"oneOf": [
					{ "$ref": "summationRuleSchema.json" },
					{ "$ref": "cumulationRuleSchema.json" }
				]
			}
		},
		"ballotEncoding": {
			"description": "Identifier of the ballot encoding scheme",
			"type": "string"
		}
	},
	"required": ["id", "type", "title", "options", "rules", "ballotEncoding"]
}

=== bfh-evg/univote2/admin-client/json-schemas/examples/sub-2015/electionIssues.json
[
	{
		"id": 1,
		"type": "listElection",
		"title": {
			"de": "Wahlen des SUB-StudentInnenrates 2015",
			"fr": "Élection du conseil des étudiant-e-s SUB 2015",
			"en": "SUB Elections 2015"
		},
		"description": {
			"de": "Der Wahlzettel kann einer Liste zugeordnet werden und maximal 40 Kandidierende aus verschiedenen Listen enthalten. Einzelne Kandidierende können bis zu dreimal aufgeführt werden. Enthält ein Wahlzettel weniger als 40 Kandidierende, so zählen die fehlenden Einträge als Zusatzstimmen für die ausgewählte Liste. Wenn keine Liste angegeben ist, verfallen diese Stimmen.",
			"fr": "Le bulletin de vote peut comporter au maximum 40 candidats. Il peut comporter des candidats de listes différentes. Chaque électeur peut cumuler jusqu’à trois suffrages sur un candidat. Le bulletin de vote peut-être attribué à une liste. Si un bulletin de vote contient un nombre de candidats inférieurs à 40, les lignes laissées en blanc sont considérées comme autant de suffrages complémentaires attribués à la liste choisie. Si aucune liste n’est indiquée, ces suffrages  sont considérés comme périmés.",
			"en": "Your ballot paper can include up to 40 candidates from all lists. It can include candidates from different lists. You may vote for each candidate up to three times. You can assign a list to your ballot. If you vote for less than 40 candidates, the missing entries will count as list votes for the chosen list. If you do not assign a list, they will expire and count as empty votes."
		},
		"options": [
			{
				"id": 1,
				"type": "list",
				"number": "1",
				"listName": "Tuxpartei",
				"partyName": "tux"
			},
			{
				"id": 2,
				"type": "candidate",
				"number": "1.1",
				"lastName": "Vuilleumier",
				"firstName": "Sebastian",
				"sex": "M",
				"yearOfBirth": 1988,
				"studyBranch": "Humanmedizin",
				"studyDegree": "MA",
				"studySemester": 10,
				"status": "OLD",
				"listId": 1,
				"listPositions": [1, 2]
			},
			{
				"id": 3,
				"type": "candidate",
				"number": "1.2",
				"lastName": "Schmid",
				"firstName": "Luca",
				"sex": "M",
				"yearOfBirth": 1993,
				"studyBranch": "Humanmedizin",
				"studyDegree": "BA",
				"studySemester": 2,
				"listId": 1,
				"listPositions": [3, 4]
			},
			{
				"id": 4,
				"type": "candidate",
				"number": "1.3",
				"lastName": "Stolz",
				"firstName": "Marcel",
				"sex": "M",
				"yearOfBirth": 1989,
				"studyBranch": "Informatik",
				"studyDegree": "MA",
				"studySemester": 3,
				"status": "OLD",
				"listId": 1,
				"listPositions": [5, 6]
			},
			{
				"id": 5,
				"type": "list",
				"number": "2",
				"listName": "Junge Grüne Uni Bern",
				"partyName": "jg"
			},
			{
				"id": 6,
				"type": "candidate",
				"number": "2.1",
				"lastName": "Oppold",
				"firstName": "Malvin",
				"sex": "M",
				"studyBranch": "Politikwissenschaft",
				"studyDegree": "MA",
				"studySemester": 5,
				"status": "OLD",
				"listId": 5,
				"listPositions": [1, 2]
			},
			{
				"id": 7,
				"type": "candidate",
				"number": "2.2",
				"lastName": "Zingg",
				"firstName": "Flavia",
				"sex": "F",
				"studyBranch": "Medizin",
				"studyDegree": "BA",
				"studySemester": 3,
				"status": "OLD",
				"listId": 5,
				"listPositions": [3, 4]
			},
			{
				"id": 8,
				"type": "candidate",
				"number": "2.3",
				"lastName": "Stalder",
				"firstName": "Lorenz",
				"sex": "M",
				"studyBranch": "Rechtswissenschaft",
				"studyDegree": "MA",
				"studySemester": 1,
				"status": "OLD",
				"listId": 5,
				"listPositions": [5, 6]
			},
			{
				"id": 9,
				"type": "candidate",
				"number": "2.4",
				"lastName": "Schär",
				"firstName": "Rahel",
				"sex": "F",
				"studyBranch": "Rechtswissenschaft",
				"studyDegree": "MA",
				"studySemester": 5,
				"status": "OLD",
				"listId": 5,
				"listPositions": [7, 8]
			},
			{
				"id": 10,
				"type": "candidate",
				"number": "2.5",
				"lastName": "Tempelmann",
				"firstName": "Jochen",
				"sex": "M",
				"studyBranch": "Geographie",
				"studyDegree": "BA",
				"studySemester": 6,
				"status": "OLD",
				"listId": 5,
				"listPositions": [9, 10]
			},
			{
				"id": 11,
				"type": "candidate",
				"number": "2.6",
				"lastName": "Sollberger",
				"firstName": "Sophia",
				"sex": "F",
				"studyBranch": "Biologie",
				"studyDegree": "BA",
				"studySemester": 2,
				"status": "OLD",
				"listId": 5,
				"listPositions": [11, 12]
			},
			{
				"id": 12,
				"type": "candidate",
				"number": "2.7",
				"lastName": "Seiler",
				"firstName": "Christoph",
				"sex": "M",
				"studyBranch": "Rechtswissenschaft",
				"studyDegree": "MA",
				"studySemester": 4,
				"status": "OLD",
				"listId": 5,
				"listPositions": [13, 14]
			},
			{
				"id": 13,
				"type": "candidate",
				"number": "2.8",
				"lastName": "Kaita",
				"firstName": "Anna",
				"sex": "F",
				"studyBranch": "Wirtschaftswissenschaften",
				"studyDegree": "BA",
				"studySemester": 4,
				"status": "OLD",
				"listId": 5,
				"listPositions": [15, 16]
			},
			{
				"id": 14,
				"type": "candidate",
				"number": "2.9",
				"lastName": "Sollberger",
				"firstName": "Leonie",
				"sex": "F",
				"studyBranch": "Rechtswissenschaft",
				"studyDegree": "BA",
				"studySemester": 4,
				"status": "NEW",
				"listId": 5,
				"listPositions": [17, 18]
			},
			{
				"id": 15,
				"type": "candidate",
				"number": "2.1",
				"lastName": "Seiler",
				"firstName": "Catarina",
				"sex": "F",
				"studyBranch": "Psychologie",
				"studyDegree": "BA",
				"studySemester": 4,
				"status": "NEW",
				"listId": 5,
				"listPositions": [19, 20]
			},
			{
				"id": 16,
				"type": "candidate",
				"number": "2.11",
				"lastName": "König",
				"firstName": "Emilie",
				"sex": "F",
				"studyBranch": "Politikwissenschaft",
				"studyDegree": "MA",
				"studySemester": 5,
				"status": "NEW",
				"listId": 5,
				"listPositions": [21]
			},
			{
				"id": 17,
				"type": "candidate",
				"number": "2.12",
				"lastName": "Schlunegger",
				"firstName": "Lea",
				"sex": "F",
				"studyBranch": "Rechtswissenschaft",
				"studyDegree": "MA",
				"studySemester": 4,
				"status": "NEW",
				"listId": 5,
				"listPositions": [22]
			},
			{
				"id": 18,
				"type": "candidate",
				"number": "2.13",
				"lastName": "Steiner",
				"firstName": "Samuel",
				"sex": "M",
				"studyBranch": "Soziologie",
				"studyDegree": "MA",
				"studySemester": 2,
				"status": "NEW",
				"listId": 5,
				"listPositions": [23]
			},
			{
				"id": 19,
				"type": "candidate",
				"number": "2.14",
				"lastName": "Nägler",
				"firstName": "Leonie",
				"sex": "F",
				"studyBranch": "Sozialwissenschaften",
				"studyDegree": "BA",
				"studySemester": 8,
				"status": "NEW",
				"listId": 5,
				"listPositions": [24]
			},
			{
				"id": 20,
				"type": "candidate",
				"number": "2.15",
				"lastName": "Häni",
				"firstName": "Eugénie",
				"sex": "F",
				"studyBranch": "Politikwissenschaft",
				"studyDegree": "MA",
				"studySemester": 4,
				"status": "NEW",
				"listId": 5,
				"listPositions": [25]
			},
			{
				"id": 21,
				"type": "candidate",
				"number": "2.16",
				"lastName": "Farner",
				"firstName": "Rebecca",
				"sex": "F",
				"studyBranch": "Religionswissenschaften",
				"studyDegree": "BA",
				"studySemester": 6,
				"status": "NEW",
				"listId": 5,
				"listPositions": [26]
			},
			{
				"id": 22,
				"type": "candidate",
				"number": "2.17",
				"lastName": "Widmer",
				"firstName": "Simone",
				"sex": "F",
				"studyBranch": "Geschichte",
				"studyDegree": "BA",
				"studySemester": 10,
				"status": "NEW",
				"listId": 5,
				"listPositions": [27]
			},
			{
				"id": 23,
				"type": "list",
				"number": "3",
				"listName": "WIR \u2013 Wirtschaftswissenschaften im Rat",
				"partyName": "wir"
			},
			{
				"id": 24,
				"type": "candidate",
				"number": "3.1",
				"lastName": "Eichenberger",
				"firstName": "Milena",
				"sex": "F",
				"studyBranch": "BWL",
				"studyDegree": "BA",
				"studySemester": 6,
				"status": "NEW",
				"listId": 23,
				"listPositions": [1, 2]
			},
			{
				"id": 25,
				"type": "candidate",
				"number": "3.2",
				"lastName": "Collalti",
				"firstName": "Dino",
				"sex": "M",
				"yearOfBirth": 1993,
				"studyBranch": "VWL",
				"studyDegree": "BA",
				"studySemester": 5,
				"status": "NEW",
				"listId": 23,
				"listPositions": [3, 4]
			},
			{
				"id": 26,
				"type": "candidate",
				"number": "3.3",
				"lastName": "Schlittler",
				"firstName": "Katharina",
				"sex": "F",
				"studyBranch": "BWL",
				"studyDegree": "BA",
				"studySemester": 2,
				"status": "NEW",
				"listId": 23,
				"listPositions": [5, 6]
			},
			{
				"id": 27,
				"type": "candidate",
				"number": "3.4",
				"lastName": "Affolter",
				"firstName": "Lorenz",
				"sex": "M",
				"yearOfBirth": 1994,
				"studyBranch": "BWL",
				"studyDegree": "BA",
				"studySemester": 4,
				"status": "NEW",
				"listId": 23,
				"listPositions": [7, 8]
			},
			{
				"id": 28,
				"type": "candidate",
				"number": "3.5",
				"lastName": "Huber",
				"firstName": "Viktoria",
				"sex": "F",
				"studyBranch": "BWL",
				"studyDegree": "BA",
				"studySemester": 4,
				"status": "NEW",
				"listId": 23,
				"listPositions": [9, 10]
			},
			{
				"id": 29,
				"type": "candidate",
				"number": "3.6",
				"lastName": "Wirth",
				"firstName": "Lea",
				"sex": "F",
				"studyBranch": "International and Monetary Economics",
				"studyDegree": "MA",
				"studySemester": 8,
				"status": "NEW",
				"listId": 23,
				"listPositions": [11, 12]
			},
			{
				"id": 30,
				"type": "candidate",
				"number": "3.7",
				"lastName": "Knecht",
				"firstName": "Thomas",
				"sex": "M",
				"studyBranch": "Business Administration Management",
				"studyDegree": "MA",
				"studySemester": 12,
				"status": "NEW",
				"listId": 23,
				"listPositions": [13, 14]
			},
			{
				"id": 31,
