=== bfh-evg/univote2/admin-client/json-schemas/electionDefinitionSchema.json
{
	"$schema": "http://json-schema.org/draft-04/schema",
	"title": "UniVote2: Schema of an election definition",
	"type": "object",
	"properties": {
		"title": {
			"description": "Title of the election",
			"$ref": "i18nTextSchema.json"
		},
		"administration": {
			"description": "Name of the election administration",
			"$ref": "i18nTextSchema.json"
		},
		"description": {
			"description": "Description of the election",
			"$ref": "i18nTextSchema.json"
		},
		"votingPeriodBegin": {
			"description": "Beginning date and time of the voting period (ISO 8601 format)",
			"type": "string",
			"format": "date-time"
		},
		"votingPeriodEnd": {
			"description": "End date and time of the voting period (ISO 8601 format)",
			"type": "string",
			"format": "date-time"
		}
	},
	"required": ["title", "votingPeriodBegin", "votingPeriodEnd"],
	"additionalProperties": false
}

=== bfh-evg/univote2/admin-client/src/main/resources/json-examples/sub-2015/electionDefinition.json
{
	"title": {
		"default": "Universität Bern: Wahlen des SUB-StudentInnenrates",
		"french": "Université de Berne: Élection du conseil des étudiant-e-s SUB",
		"english": "University of Bern: SUB Elections"
	},
	"administration": {
		"default": "StudentInnenschaft der Universität Bern (SUB)",
		"french": "Ensemble des étudiants de l'Université de Berne (SUB)",
		"english": "Student Body of the University of Bern (SUB)"
	},
	"votingPeriodBegin": "2015-03-08T23:00:00Z",
	"votingPeriodEnd": "2015-03-26T11:00:00Z"
}

=== bfh-evg/univote2/admin-client/json-messages/sub-2015/electionDefinition.json
{
	"title": {
		"default": "Wahlen des SUB-StudentInnenrates",
		"fr": "Élection du conseil des étudiant-e-s SUB",
		"en": "SUB Elections"
	},
	"administration": {
		"default": "Universität Bern",
		"fr": "Université de Berne",
		"en": "University of Bern"
	},
	"votingPeriodBegin": "2015-03-08T23:00:00Z",
	"votingPeriodEnd": "2015-09-26T11:00:00Z"
}

=== bfh-evg/univote2/json-schemas/example-data/sub-2015/electionDefinition.json
{
	"title": {
			"en": "University of Berne: SUB Elections",
			"de": "Universität Bern: Wahlen des SUB-StudentInnenrates",
			"fr": "Université de Berne: Élection du conseil des étudiant-e-s SUB"
	},
	"description": {
			"en": "Your ballot paper can include up to 40 candidates from all lists. It can include candidates from different lists. You may vote for each candidate up to three times. You can assign a list to your ballot. If you vote for less than 40 candidates, the missing entries will count as list votes for the chosen list. If you do not assign a list, they will expire and count as empty votes.",
			"de": "Der Wahlzettel kann einer Liste zugeordnet werden und maximal 40 Kandidierende aus verschiedenen Listen enthalten. Einzelne Kandidierende können bis zu dreimal aufgeführt werden. Enthält ein Wahlzettel weniger als 40 Kandidierende, so zählen die fehlenden Einträge als Zusatzstimmen für die ausgewählte Liste. Wenn keine Liste angegeben ist, verfallen diese Stimmen.",
			"fr": "Le bulletin de vote peut comporter au maximum 40 candidats. Il peut comporter des candidats de listes différentes. Chaque électeur peut cumuler jusqu’à trois suffrages sur un candidat. Le bulletin de vote peut-être attribué à une liste. Si un bulletin de vote contient un nombre de candidats inférieurs à 40, les lignes laissées en blanc sont considérées comme autant de suffrages complémentaires attribués à la liste choisie. Si aucune liste n’est indiquée, ces suffrages  sont considérés comme périmés."
	},
	"votingPeriodBegin": "2015-03-08T23:00:00Z",
	"votingPeriodEnd": "2015-03-26T11:00:00Z"
}
