=== bfh-evg/univote2/json-schemas/server/certificateSchema.json
{
	"title": "Schema for UniCert certificates",
	"description": "This schema describes the format of a UniCert certificate in JSON format",
	"type":"object",
	"$schema": "http://json-schema.org/draft-04/schema",
	"properties": {
		"commonName": {
			"type": "string",
			"description": "Common name of certificate owner"
		},	
		"uniqueIdentifier": {
			"type": "string",
			"description":  "Unique identifier of certificate owner"
		},
		"organisation": {
			"type": "string",
			"description": "Organisation of certificate owner"
		},
		"organisationUnit": {
			"type": "string",
			"description": "Organisation unit of certificate owner"
		},
		"countryName": {
			"type": "string",
			"description": "Country of certificate owner"
		},
		"state": {
			"type": "string",
			"description": "State of certificate owner"
		},
		"locality": {
			"type": "string",
			"description": "Locality certificate owner"
		},
		"surname": {
			"type": "string",
			"description": "Surname of certificate owner"
		},
		"givenName": {
			"type": "string",
			"description": "Given name of certificate owner"
		},
	   	"issuer": {
			"type": "string",
			"description": "Issuer of the certificate"
		},
		"serialNumber": {
			"type":"string",
			"description": "Serial number of the certificate"
		},
		"validFrom": {
			"type": "string",
			"description": "Date when certificate starts to be valid"
		},
		"validUntil": {
			"type": "string",
			"description": "Date when certificate stops to be valid"
		}, 
		"applicationIdentifier": {
			"type": "string",
			"description": "Application the certificate has been issued for"
		},
		"roles": {
			"type":"array",
			"description": "Role inside an application the certificate has been issued for",
			"items": {
				"type":"string"
			}
		},
		"identityProvider": {
			"type": "string",
			"description": "Identity provider used to verify the identity of the certificate owner"
		},
		"pem": {
			"type": "string",
			"description": "Certificate in PEM format"
		}
	},
	"additionalProperties": false,
	"required": ["commonName", "issuer", "serialNumber", "validFrom", "validUntil", "identityProvider", "pem" ]
}

=== bfh-evg/univote2/admin-client/src/main/resources/json-examples/ch-2015-06-14/voterCertificates.json
[
	{
		"commonName": "XXXXXXXXX",
		"uniqueIdentifier": "XXXXXXXXXXX",
		"organisation": "bfh.ch",
		"issuer": "CN=UniCert BFH",
		"serialNumber": "765428343514349",
		"validFrom": "2015-06-22T12:35:42.000+0000",
		"validUntil": "2025-06-22T12:35:42.000+0000",
		"applicationIdentifier": "UniVote",
		"roles": [ "Voter" ],
		"identityProvider": "SwitchAAI",
		"pem": "UsAMBYxFDASBWQWFgNasdVBAMMnCdfZIMB4XDTE1MDYyMjEjEAWUWQyMzU0MloXDTI1MDYyMfjEyMzUigM"
	},
	{
		"commonName": "XXXXXXXXX",
		"uniqueIdentifier": "XXXXXXXXXXX",
		"organisation": "bfh.ch",
		"issuer": "CN=UniCert BFH",
		"serialNumber": "765428343514349",
		"validFrom": "2015-06-22T12:35:42.000+0000",
		"validUntil": "2025-06-22T12:35:42.000+0000",
		"applicationIdentifier": "UniVote",
		"roles": [ "Voter" ],
		"identityProvider": "SwitchAAI",
		"pem": "UsAMBYxFDASBWQWFgNasdVBAMMnCdfZIMB4XDTE1MDYyMjEjEAWUWQyMzU0MloXDTI1MDYyMfjEyMzUigM"
	}
]

=== bfh-evg/univote2/json-schemas/examples/ch-2015-06-14/certificate.json
{
	"commonName": "XXXXXXXXX",
	"uniqueIdentifier": "XXXXXXXXXXX",
	"organisation": "bfh.ch",
	"issuer": "CN=UniCert BFH",
	"serialNumber": "765428343514349",
	"validFrom": "2015-06-22T12:35:42Z",
	"validUntil": "2025-06-22T12:35:42Z",
	"applicationIdentifier": "UniVote",
	"roles": ["Voter"],
	"identityProvider": "SwitchAAI",
	"pem": "UsAMBYxFDASBWQWFgNasdVBAMMnCdfZIMB4XDTE1MDYyMjEjEAWUWQyMzU0MloXDTI1MDYyMfjEyMzUigM"
}
